"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { motion } from "framer-motion-3d";
import { type ModelComponent } from "../types";

export const PhoneModel: ModelComponent = ({
  onReady,
  ready,
  rotation,
  position,
  scale,
}) => {
  const { nodes, materials } = useGLTF("/3d/models/p8pc.glb");

  useEffect(() => {
    onReady();
  }, [onReady]);

  return !ready ? null : (
    <motion.group
      rotation={[rotation.x, rotation.y, rotation.z]}
      position={[0, position.y, 0]}
      initial={false}
      animate={{
        scale,
        transition: {
          duration: 4,
          ease: "easeOut",
          scale: {
            duration: 0.3,
            ease: "easeOut",
          },
        },
      }}
    >
      <group position={[0, -0.077, 0.002]} scale={0.938}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.deviceback.geometry}
          material={materials["material.back"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.devicecamera.geometry}
          material={materials["material.camera"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.devicecameraglass.geometry}
          material={materials["material.camera.glass"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.devicelogo.geometry}
          material={materials["material.logo"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.devicescreen.geometry}
          material={materials["material.screen"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.devicebody_1.geometry}
          material={materials["material.body"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.devicebody_2.geometry}
          material={materials["material.body.cameraframe"]}
        />
      </group>
    </motion.group>
  );
};

useGLTF.preload("/3d/models/p8pc.glb");
