import { Figtree } from "next/font/google";
import { type FunctionComponent, type ReactNode } from "react";
import { NavigationBar } from "@/components/shared/navigation-bar";
import { SafeArea } from "@/components/shared/safe-area";
import "./global.css";
import { Providers } from "@/components/shared/providers";
import { SmoothScroller } from "@/components/shared/smooth-scroller";

const figtreeFont = Figtree({ subsets: ["latin"] });

export const metadata = {
  title: "Leyton Blackler",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: FunctionComponent<RootLayoutProps> = ({ children }) => (
  /**
   * TODO: Change HTML element background color to match light/dark theme to
   * prevent showing white when scrolling past top and bottoms
   */
  <html lang="en" className="bg-gray-50 dark:bg-gray-950">
    <body className={figtreeFont.className}>
      <Providers>
        <main>
          <SmoothScroller id="main-scroll-container">
            <SafeArea>{children}</SafeArea>
          </SmoothScroller>
        </main>
        <NavigationBar />
      </Providers>
    </body>
  </html>
);

export default RootLayout;
