"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { motion } from "framer-motion-3d";
import { type ModelComponent } from "../types";

export const LaptopModel: ModelComponent = ({
  onReady,
  ready,
  rotation,
  position,
  scale,
}) => {
  const { nodes, materials } = useGLTF("/3d/models/mblid.glb");

  useEffect(() => {
    onReady();
  }, [onReady]);

  return !ready ? null : (
    <motion.group
      rotation={[rotation.x, rotation.y, rotation.z]}
      position={[0, position.y, 0]}
      initial={false}
      animate={{
        scale,
        transition: {
          scale: {
            duration: 0.3,
            ease: "easeOut",
          },
        },
      }}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DAuseNOrQKyrxKl.geometry}
            material={materials.yVmFXNTCIwNkqVT}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.eAcvqfZlEdoxHsj.geometry}
            material={materials.IlNnjEDxsExlBOr}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.gkxaPoMYYRpyVMR.geometry}
            material={materials.iPZiEncThgnBMJv}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.guoofBSjCEiTIJr.geometry}
            material={materials.JjuwNKnMBUdtRLb}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.KCEhahuknsxQOxv.geometry}
            material={materials.HpEeGHRuOqfcIZU}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mUrIWHenIQKVHcb.geometry}
            material={materials.BMKLbAPYqPmfArt}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.NdRhLFCrSxRNTxn.geometry}
            material={materials.BMKLbAPYqPmfArt}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.NgmQYtxXWDmCavo.geometry}
            material={materials.SKOFticEGTqECbB}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.NqLxSKdAypgOdPC.geometry}
            material={materials.initialShadingGroup}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.NWErafhynAfYQEz.geometry}
            material={materials.pZbDFXVUkfRwjmQ}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.piXptsgcOfaGWrM.geometry}
            material={materials.WLATjirhQCUYAAG}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PSIiVLWbMOjTmDb.geometry}
            material={materials.SKOFticEGTqECbB}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PTxrSKzcEmHVtif.geometry}
            material={materials.VfcxYmbOfnqunYx}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.QFFLzaWPRnuQYJR.geometry}
            material={materials.hPcehRUjcLAosED}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.QHqPxKdexBoFnAK.geometry}
            material={materials.zaEqorbaeeADKgU}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.QMBrsnrwfcVKELm.geometry}
            material={materials.VqwNZwmDotIMflD}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.QYMcPaZnXQfyXcJ.geometry}
            material={materials.NQXltfOcKPZPQdI}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.rIsAbujsARaHSub.geometry}
            material={materials.jAWKNAaRBMlZYro}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.RjGOdbHqvxkiDns.geometry}
            material={materials.lbGSuJJwEsUTzIm}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.RkSurqpnfNMQZfv.geometry}
            material={materials.zWLcvvnJhbcTEtJ}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SjSNuZdtWKZRuoq.geometry}
            material={materials.mpJhsaJJZPPWMEX}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SjXIFRJFXEqYDUr.geometry}
            material={materials.PCfVLhSpFVCvRmc}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.TCGsaoyNbPKzeSS.geometry}
            material={materials.yVmFXNTCIwNkqVT}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tEHnKyDsqJuxIpz.geometry}
            material={materials.yVmFXNTCIwNkqVT}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tEwRkclpxjXZzil.geometry}
            material={materials.UPMcPXFSRXevSGt}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.UxiDBlCRfXiMBzT.geometry}
            material={materials.zWLcvvnJhbcTEtJ}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.vivXPkdlqllUnrl.geometry}
            material={materials.XNDkEZQapqqDHpk}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.VqfccLWHjnpnmIO.geometry}
            material={materials.BMKLbAPYqPmfArt}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.WPFmzKypKbUYgQT.geometry}
            material={materials.lbGSuJJwEsUTzIm}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wXiLpiodZWNDroe.geometry}
            material={materials.HPAOpCInJKBtaOC}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.xjTvBwZFGvSMOud.geometry}
            material={materials.hPcehRUjcLAosED}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.xlRLalLTesirCGW.geometry}
            material={materials.hPcehRUjcLAosED}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.YJMoQnvBNpTrgeH.geometry}
            material={materials.PCfVLhSpFVCvRmc}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ZlizOzukFeXwbga.geometry}
            material={materials.kOcboIDeohDRqCf}
          />
        </group>
      </group>
      <group position={[0, -0.413, -11.346]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.matte.geometry}
          material={materials.matte}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.back_1.geometry}
          material={materials.blackmatte}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.back_2.geometry}
          material={materials.aluminium}
        />
      </group>
    </motion.group>
  );
};

useGLTF.preload("/3d/models/mblid.glb");
